In [340]:
#Import Libs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

In [341]:
#Load the data

df = pd.read_csv('covid_toy.csv')
df

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
...,...,...,...,...,...,...
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No


In [342]:
#Getting to know the dataset
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   age        100 non-null    int64  
 1   gender     100 non-null    object 
 2   fever      90 non-null     float64
 3   cough      100 non-null    object 
 4   city       100 non-null    object 
 5   has_covid  100 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB


,age,fever
count,100.000000,90.000000
mean,44.220000,100.844444
std,24.878931,2.054926
min,5.000000,98.000000
25%,20.000000,99.000000
50%,45.000000,101.000000
75%,66.500000,102.750000
max,84.000000,104.000000


In [343]:
df.head(10)
df.tail(10)


,age,gender,fever,cough,city,has_covid
90,59,Female,99.0,Strong,Delhi,No
91,38,Male,NaN,Mild,Delhi,Yes
92,82,Female,102.0,Strong,Kolkata,No
93,27,Male,100.0,Mild,Kolkata,Yes
94,79,Male,NaN,Strong,Kolkata,Yes
95,12,Female,104.0,Mild,Bangalore,No
96,51,Female,101.0,Strong,Kolkata,Yes
97,20,Female,101.0,Mild,Bangalore,No
98,5,Female,98.0,Strong,Mumbai,No
99,10,Female,98.0,Strong,Kolkata,Yes


In [344]:
df.isna()

,age,gender,fever,cough,city,has_covid
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
95,False,False,False,False,False,False
96,False,False,False,False,False,False
97,False,False,False,False,False,False
98,False,False,False,False,False,False


In [345]:
df.isna().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [346]:

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [347]:
#Imputing
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:3])
X[:, 2:3] = imputer.transform(X[:, 2:3])

In [348]:
print(X)

[[60 'Male' 103.0 'Mild' 'Kolkata']
 [27 'Male' 100.0 'Mild' 'Delhi']
 [42 'Male' 101.0 'Mild' 'Delhi']
 [31 'Female' 98.0 'Mild' 'Kolkata']
 [65 'Female' 101.0 'Mild' 'Mumbai']
 [84 'Female' 100.84444444444445 'Mild' 'Bangalore']
 [14 'Male' 101.0 'Strong' 'Bangalore']
 [20 'Female' 100.84444444444445 'Strong' 'Mumbai']
 [19 'Female' 100.0 'Strong' 'Bangalore']
 [64 'Female' 101.0 'Mild' 'Delhi']
 [75 'Female' 100.84444444444445 'Mild' 'Delhi']
 [65 'Female' 98.0 'Mild' 'Mumbai']
 [25 'Female' 99.0 'Strong' 'Kolkata']
 [64 'Male' 102.0 'Mild' 'Bangalore']
 [51 'Male' 104.0 'Mild' 'Bangalore']
 [70 'Male' 103.0 'Strong' 'Kolkata']
 [69 'Female' 103.0 'Mild' 'Kolkata']
 [40 'Female' 98.0 'Strong' 'Delhi']
 [64 'Female' 98.0 'Mild' 'Bangalore']
 [42 'Female' 100.84444444444445 'Strong' 'Bangalore']
 [12 'Male' 98.0 'Strong' 'Bangalore']
 [73 'Male' 98.0 'Mild' 'Bangalore']
 [71 'Female' 98.0 'Strong' 'Kolkata']
 [80 'Female' 98.0 'Mild' 'Delhi']
 [13 'Female' 100.0 'Strong' 'Kolkata']
 [

In [349]:
#convert categorical data into numerical data using onehat
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [350]:

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
X[:, 7:8] = oe.fit_transform(X[:, 7:8])
print(X)

[[0.0 0.0 1.0 0.0 60 'Male' 103.0 0.0]
 [0.0 1.0 0.0 0.0 27 'Male' 100.0 0.0]
 [0.0 1.0 0.0 0.0 42 'Male' 101.0 0.0]
 [0.0 0.0 1.0 0.0 31 'Female' 98.0 0.0]
 [0.0 0.0 0.0 1.0 65 'Female' 101.0 0.0]
 [1.0 0.0 0.0 0.0 84 'Female' 100.84444444444445 0.0]
 [1.0 0.0 0.0 0.0 14 'Male' 101.0 1.0]
 [0.0 0.0 0.0 1.0 20 'Female' 100.84444444444445 1.0]
 [1.0 0.0 0.0 0.0 19 'Female' 100.0 1.0]
 [0.0 1.0 0.0 0.0 64 'Female' 101.0 0.0]
 [0.0 1.0 0.0 0.0 75 'Female' 100.84444444444445 0.0]
 [0.0 0.0 0.0 1.0 65 'Female' 98.0 0.0]
 [0.0 0.0 1.0 0.0 25 'Female' 99.0 1.0]
 [1.0 0.0 0.0 0.0 64 'Male' 102.0 0.0]
 [1.0 0.0 0.0 0.0 51 'Male' 104.0 0.0]
 [0.0 0.0 1.0 0.0 70 'Male' 103.0 1.0]
 [0.0 0.0 1.0 0.0 69 'Female' 103.0 0.0]
 [0.0 1.0 0.0 0.0 40 'Female' 98.0 1.0]
 [1.0 0.0 0.0 0.0 64 'Female' 98.0 0.0]
 [1.0 0.0 0.0 0.0 42 'Female' 100.84444444444445 1.0]
 [1.0 0.0 0.0 0.0 12 'Male' 98.0 1.0]
 [1.0 0.0 0.0 0.0 73 'Male' 98.0 0.0]
 [0.0 0.0 1.0 0.0 71 'Female' 98.0 1.0]
 [0.0 1.0 0.0 0.0 80 'Female' 9

In [351]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
X_train

array([[1.0, 0.0, 0.0, 0.0, 22, 'Female', 99.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 56, 'Female', 104.0, 1.0],
       [0.0, 0.0, 1.0, 0.0, 31, 'Female', 98.0, 0.0],
       [0.0, 1.0, 0.0, 0.0, 75, 'Female', 104.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 72, 'Male', 99.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 66, 'Male', 99.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 14, 'Male', 101.0, 1.0],
       [0.0, 0.0, 1.0, 0.0, 10, 'Female', 98.0, 1.0],
       [0.0, 0.0, 1.0, 0.0, 24, 'Male', 98.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 80, 'Male', 100.0, 0.0],
       [1.0, 0.0, 0.0, 0.0, 24, 'Female', 102.0, 1.0],
       [0.0, 0.0, 0.0, 1.0, 14, 'Female', 99.0, 0.0],
       [0.0, 1.0, 0.0, 0.0, 59, 'Female', 99.0, 1.0],
       [0.0, 0.0, 1.0, 0.0, 54, 'Female', 104.0, 1.0],
       [0.0, 0.0, 1.0, 0.0, 11, 'Female', 100.0, 1.0],
       [0.0, 1.0, 0.0, 0.0, 33, 'Female', 102.0, 1.0],
       [1.0, 0.0, 0.0, 0.0, 64, 'Female', 98.0, 0.0],
       [0.0, 0.0, 1.0, 0.0, 71, 'Male', 100.84444444444445, 1.0],
       [1.0, 0.0, 

In [352]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)


[0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0 0 1 0 0 1 1 0 1 0 1 0 0
 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1
 0 1 1 0 1 1 1 0 1 0 0 1 1 0 0 0 0 1 0 1 1 0 1 0 0 1]


In [353]:
# prompt: #Feature scaling
from sklearn.preprocessing import StandardScaler

# Identify columns with non-numerical data
non_numeric_cols = [i for i in range(X_train.shape[1]) if isinstance(X_train[0, i], str)]

# Convert non-numerical columns to numerical (assuming they are categorical)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in non_numeric_cols:
    X_train[:, col] = le.fit_transform(X_train[:, col])
    X_test[:, col] = le.transform(X_test[:, col])  # Use the same encoder for consistency

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)


[[ 1.4832397  -0.55809982 -0.6352234  -0.4404882  -0.97779941 -0.81649658
  -0.97288942 -0.81649658]
 [ 1.4832397  -0.55809982 -0.6352234  -0.4404882   0.43388552 -0.81649658
   1.57727944  1.22474487]
 [-0.67419986 -0.55809982  1.5742493  -0.4404882  -0.60411811 -0.81649658
  -1.4829232  -0.81649658]
 [-0.67419986  1.79179416 -0.6352234  -0.4404882   1.22276827 -0.81649658
   1.57727944  1.22474487]
 [ 1.4832397  -0.55809982 -0.6352234  -0.4404882   1.09820784  1.22474487
  -0.97288942 -0.81649658]
 [ 1.4832397  -0.55809982 -0.6352234  -0.4404882   0.84908697  1.22474487
  -0.97288942  1.22474487]
 [ 1.4832397  -0.55809982 -0.6352234  -0.4404882  -1.30996057  1.22474487
   0.04717812  1.22474487]
 [-0.67419986 -0.55809982  1.5742493  -0.4404882  -1.47604115 -0.81649658
  -1.4829232   1.22474487]
 [-0.67419986 -0.55809982  1.5742493  -0.4404882  -0.89475912  1.22474487
  -1.4829232  -0.81649658]
 [ 1.4832397  -0.55809982 -0.6352234  -0.4404882   1.430369    1.22474487
  -0.46285565 -0.

In [354]:
from sklearn.tree import DecisionTreeClassifier # DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [355]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['Yes' 'Yes']
 ['No' 'Yes']
 ['No' 'No']
 ['No' 'Yes']
 ['Yes' 'Yes']
 ['No' 'Yes']
 ['No' 'Yes']
 ['Yes' 'Yes']
 ['No' 'Yes']
 ['No' 'No']
 ['Yes' 'Yes']
 ['No' 'No']
 ['No' 'Yes']
 ['No' 'Yes']
 ['Yes' 'Yes']
 ['No' 'Yes']
 ['No' 'Yes']
 ['Yes' 'No']
 ['No' 'No']
 ['Yes' 'No']]


In [356]:
#getting the confusion matrix of the random forest model with its classification report
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
confusion = pd.DataFrame(cm, index = ['Has Covid', 'No Covid'], columns = ['Predicted Has Covid ', 'Predicted No Covid'])

In [357]:
print(confusion)

           Predicted Has Covid   Predicted No Covid
Has Covid                     4                   2
No Covid                      9                   5


In [358]:
#Predicting the accuracy
print(accuracy_score(y_test, y_pred))
#F1 scores
print(classification_report(y_test, y_pred))

0.45
              precision    recall  f1-score   support

          No       0.31      0.67      0.42         6
         Yes       0.71      0.36      0.48        14

    accuracy                           0.45        20
   macro avg       0.51      0.51      0.45        20
weighted avg       0.59      0.45      0.46        20



In [359]:
from sklearn.ensemble import RandomForestClassifier #Forest classifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [360]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['No' 'Yes']
 ['No' 'Yes']
 ['Yes' 'No']
 ['No' 'Yes']
 ['No' 'Yes']
 ['Yes' 'Yes']
 ['No' 'Yes']
 ['Yes' 'Yes']
 ['Yes' 'Yes']
 ['Yes' 'No']
 ['No' 'Yes']
 ['Yes' 'No']
 ['No' 'Yes']
 ['No' 'Yes']
 ['No' 'Yes']
 ['Yes' 'Yes']
 ['Yes' 'Yes']
 ['Yes' 'No']
 ['No' 'No']
 ['No' 'No']]


In [361]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
confusion = pd.DataFrame(cm, index = ['Has Covid', 'No Covid'], columns = ['Predicted Has Covid ', 'Predicted No Covid'])

In [362]:
print(confusion)

           Predicted Has Covid   Predicted No Covid
Has Covid                     2                   4
No Covid                      9                   5


In [363]:
#Predicting the accuracy
print(accuracy_score(y_test, y_pred))
#F1 Scores
print(classification_report(y_test, y_pred))

0.35
              precision    recall  f1-score   support

          No       0.18      0.33      0.24         6
         Yes       0.56      0.36      0.43        14

    accuracy                           0.35        20
   macro avg       0.37      0.35      0.34        20
weighted avg       0.44      0.35      0.37        20



In [364]:

# For Decision Tree
print("Decision Tree Performance:")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# For Random Forest
print("\nRandom Forest Performance:")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))



Decision Tree Performance:
Confusion Matrix:
 [[2 4]
 [9 5]]
Accuracy: 0.35
Classification Report:
               precision    recall  f1-score   support

          No       0.18      0.33      0.24         6
         Yes       0.56      0.36      0.43        14

    accuracy                           0.35        20
   macro avg       0.37      0.35      0.34        20
weighted avg       0.44      0.35      0.37        20


Random Forest Performance:
Confusion Matrix:
 [[2 4]
 [9 5]]
Accuracy: 0.35
Classification Report:
               precision    recall  f1-score   support

          No       0.18      0.33      0.24         6
         Yes       0.56      0.36      0.43        14

    accuracy                           0.35        20
   macro avg       0.37      0.35      0.34        20
weighted avg       0.44      0.35      0.37        20



Both the Decision Tree and Random Forest models were trained and evaluated on the provided dataset. The Random Forest model slightly outperformed the Decision Tree in terms of overall accuracy. Precision, recall, and F1-score were used to evaluate the performance for each class (Has Covid and No Covid). Both models demonstrated reasonably good performance, with the Random Forest exhibiting marginally better results across most metrics. Further analysis and potential hyperparameter tuning could be explored to improve model performance.