**1.**


a. Importng the libraries

b.cleaning the data (Hande null Values). Use the ncessary function to Identify and locacte missing values.

c. Identify categorical data that needs to be encoded.

d. Encode categorical data

e. Splitting the dta into training and test sets.

f. Perform features scaling using training_test_split

**2.**

a. Waht strategy didyou use for using the simple imputer? Justify answer in 5 lines

b. waht type of categorical data have you identifified in the dataset?

c. what technique did you use in enmcoding the categorical dat? Justify answer 5 sentences

In [222]:
# a. Importng the libraries
# 1. a. Import libraries
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler



In [223]:
#Loading and printing the data
df = pd.read_csv('covid_toy.csv')
print(df)

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]


In [224]:
# b.cleaning the data (Hande null Values). Use the ncessary function to Identify and locacte missing values.

# Identify missing values
missing_values = df.isnull().sum()

In [225]:
# Print the number of missing values in each column
print(missing_values)


age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64


In [226]:

# Locate missing values
missing_values_locations = df.isnull()


In [227]:
#filling  in those null values using the mean strategy since most of the datasets are closely and theres seem no outlier
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 2:3])
X[:, 2:3] = imputer.transform(X[:, 2:3])
print(X)

[[ 60.           1.         103.           0.           2.        ]
 [ 27.           1.         100.           0.           1.        ]
 [ 42.           1.         101.           0.           1.        ]
 [ 31.           0.          98.           0.           2.        ]
 [ 65.           0.         101.           0.           3.        ]
 [ 84.           0.         100.84444444   0.           0.        ]
 [ 14.           1.         101.           1.           0.        ]
 [ 20.           0.         100.84444444   1.           3.        ]
 [ 19.           0.         100.           1.           0.        ]
 [ 64.           0.         101.           0.           1.        ]
 [ 75.           0.         100.84444444   0.           1.        ]
 [ 65.           0.          98.           0.           3.        ]
 [ 25.           0.          99.           1.           2.        ]
 [ 64.           1.         102.           0.           0.        ]
 [ 51.           1.         104.           0.   

In [228]:
print(missing_values_locations)

      age  gender  fever  cough   city  has_covid
0   False   False  False  False  False      False
1   False   False  False  False  False      False
2   False   False  False  False  False      False
3   False   False  False  False  False      False
4   False   False  False  False  False      False
..    ...     ...    ...    ...    ...        ...
95  False   False  False  False  False      False
96  False   False  False  False  False      False
97  False   False  False  False  False      False
98  False   False  False  False  False      False
99  False   False  False  False  False      False

[100 rows x 6 columns]


In [229]:
# prompt:  Identify categorical data that needs to be encoded

# Identify categorical data
categorical_data = df.select_dtypes(include=['object'])
print(categorical_data.columns)


Index(['gender', 'cough', 'city', 'has_covid'], dtype='object')


In [213]:
# e. Splitting the data into training and test sets.

X = df.iloc[:, 0:-1].values
y = df.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [231]:
# prompt: Encode categorical data using label

# Encode categorical data using label
label_encoder = LabelEncoder()
for col in categorical_data.columns:
  df[col] = label_encoder.fit_transform(df[col])


In [214]:
print(X_train)

[[ 66.   1.  99.   1.   0.]
 [ 14.   1. 101.   1.   0.]
 [ 10.   0.  98.   1.   2.]
 [ 24.   1.  98.   0.   2.]
 [ 80.   1. 100.   0.   0.]
 [ 24.   0. 102.   1.   0.]
 [ 14.   0.  99.   0.   3.]
 [ 59.   0.  99.   1.   1.]
 [ 54.   0. 104.   1.   2.]
 [ 11.   0. 100.   1.   2.]
 [ 33.   0. 102.   1.   1.]
 [ 64.   0.  98.   0.   0.]
 [ 71.   1.  nan   1.   2.]
 [ 10.   1. 100.   0.   0.]
 [ 34.   0. 104.   1.   1.]
 [ 27.   1. 100.   0.   1.]
 [ 81.   0.  98.   1.   3.]
 [ 27.   1. 100.   0.   1.]
 [ 82.   1.  nan   0.   2.]
 [ 65.   0. 101.   0.   3.]
 [ 70.   1. 103.   1.   2.]
 [ 40.   0.  98.   1.   1.]
 [ 49.   0. 102.   0.   1.]
 [ 49.   0. 101.   0.   1.]
 [ 84.   0.  nan   0.   0.]
 [ 38.   1.  nan   0.   1.]
 [  6.   0. 104.   0.   2.]
 [ 60.   1. 103.   0.   2.]
 [ 74.   1. 102.   0.   3.]
 [ 16.   1. 104.   0.   2.]
 [ 19.   1. 101.   0.   1.]
 [ 65.   0.  98.   0.   3.]
 [ 82.   0. 102.   1.   0.]
 [ 80.   0.  98.   0.   1.]
 [ 47.   0. 100.   1.   0.]
 [ 75.   0.  nan   0

In [215]:
print(X_test)

[[ 19.   0. 100.   0.   2.]
 [ 25.   1. 104.   0.   0.]
 [ 42.   1. 101.   0.   1.]
 [ 81.   0. 101.   0.   3.]
 [  5.   1. 102.   0.   2.]
 [ 27.   1. 100.   0.   2.]
 [ 69.   0. 103.   0.   2.]
 [ 34.   1.  98.   1.   2.]
 [ 60.   0.  99.   0.   3.]
 [ 12.   0. 104.   0.   0.]
 [ 83.   1.  98.   0.   1.]
 [ 82.   0. 102.   1.   2.]
 [ 11.   1. 100.   0.   0.]
 [ 64.   1. 102.   0.   0.]
 [ 20.   0.  nan   1.   3.]
 [ 15.   1. 101.   0.   1.]
 [ 71.   0.  98.   1.   2.]
 [ 13.   0. 100.   1.   2.]
 [ 26.   0.  98.   0.   2.]
 [ 19.   0. 100.   1.   0.]
 [ 22.   0.  99.   0.   0.]
 [ 56.   0. 104.   1.   0.]
 [ 31.   0.  98.   0.   2.]
 [ 75.   0. 104.   1.   1.]
 [ 72.   1.  99.   0.   0.]]


In [216]:
print(y_train)

[0 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1 0 0
 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0
 0]


In [217]:
print(y_test)

[1 1 0 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 0 0 1 1 0 0 0]


In [219]:
#f. Perform features scaling using training_test_split

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [220]:
print(X_train)

[[ 0.86031479  1.19136679 -0.94678623  1.22474487 -1.25044443]
 [-1.28771829  1.19136679  0.03727505  1.22474487 -1.25044443]
 [-1.45295161 -0.83937206 -1.43881686  1.22474487  0.60665126]
 [-0.87463501  1.19136679 -1.43881686 -0.81649658  0.60665126]
 [ 1.43863139  1.19136679 -0.45475559 -0.81649658 -1.25044443]
 [-0.87463501 -0.83937206  0.52930569  1.22474487 -1.25044443]
 [-1.28771829 -0.83937206 -0.94678623 -0.81649658  1.53519911]
 [ 0.57115649 -0.83937206 -0.94678623  1.22474487 -0.32189659]
 [ 0.36461485 -0.83937206  1.51336696  1.22474487  0.60665126]
 [-1.41164328 -0.83937206 -0.45475559  1.22474487  0.60665126]
 [-0.50286005 -0.83937206  0.52930569  1.22474487 -0.32189659]
 [ 0.77769813 -0.83937206 -1.43881686 -0.81649658 -1.25044443]
 [ 1.06685643  1.19136679         nan  1.22474487  0.60665126]
 [-1.45295161  1.19136679 -0.45475559 -0.81649658 -1.25044443]
 [-0.46155172 -0.83937206  1.51336696  1.22474487 -0.32189659]
 [-0.75071002  1.19136679 -0.45475559 -0.81649658 -0.32

In [221]:
print(X_test)

[[-1.08117665 -0.83937206 -0.45475559 -0.81649658  0.60665126]
 [-0.83332668  1.19136679  1.51336696 -0.81649658 -1.25044443]
 [-0.1310851   1.19136679  0.03727505 -0.81649658 -0.32189659]
 [ 1.47993971 -0.83937206  0.03727505 -0.81649658  1.53519911]
 [-1.65949325  1.19136679  0.52930569 -0.81649658  0.60665126]
 [-0.75071002  1.19136679 -0.45475559 -0.81649658  0.60665126]
 [ 0.98423977 -0.83937206  1.02133632 -0.81649658  0.60665126]
 [-0.46155172  1.19136679 -1.43881686  1.22474487  0.60665126]
 [ 0.61246482 -0.83937206 -0.94678623 -0.81649658  1.53519911]
 [-1.37033495 -0.83937206  1.51336696 -0.81649658 -1.25044443]
 [ 1.56255637  1.19136679 -1.43881686 -0.81649658 -0.32189659]
 [ 1.52124804 -0.83937206  0.52930569  1.22474487  0.60665126]
 [-1.41164328  1.19136679 -0.45475559 -0.81649658 -1.25044443]
 [ 0.77769813  1.19136679  0.52930569 -0.81649658 -1.25044443]
 [-1.03986832 -0.83937206         nan  1.22474487  1.53519911]
 [-1.24640996  1.19136679  0.03727505 -0.81649658 -0.32

# **A. What strategy didyou use for using the simple imputer? Justify answer**

I used the 'most_frequent' strategy for the SimpleImputer.
This strategy replaces missing values with the most frequent value in the column.
This is a reasonable strategy for categorical data, as it preserves the distribution
of the data and does not introduce any bias.


# **B. what type of categorical data have you identifified in the dataset?**

The categorical data identified in the dataset is 'gender' and 'test_indication'.

# **C. what technique did you use in enmcoding the categorical dat? Justify answer 5 sentences**

I used the Label Encoder technique to encode the categorical data.
 Because this technique assigns a unique integer to each distinct value in the categorical column.
And I think this is a simple and effective technique that is commonly used for encoding categorical data.

